server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: license

  devtools:
    restart:
      enabled: false

  datasource:
    master:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/license?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456

#  shardingsphere:
#    datasource:
#      names: ds0
#      ds0:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbcUrl: jdbc:mysql://localhost:3306/license?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#        username: root
#        password: 123456
  shardingsphere:
    enabled: false

  redis:
    database: 0 # Redis数据库索引（默认为0）
    timeout: 20000 #设置客户端超时时间，单位是毫秒，默认为2000
    password: 123456 #密码
    #单机版
    host: 127.0.0.1
    port: 6379
    #集群版
    #    cluster:
    #      max-redirects: 3  # 获取失败 最大重定向次数
    #      nodes:
    #        - 127.0.0.1:6379
    #        - 192.168.91.5:9002
    lettuce:
      pool:
        max-active: 2000 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 300 #最大空闲数
        min-idle: 0 #最小空闲数
      shutdown-timeout: 1000

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yozosoft.licenseserver.model

#分页插件配置
pagehelper:
  helperDialect: mysql  #数据库连接
  reasonable: true      #分页合理化参数,如超过最后一页修正
  page-size-zero: true  #如果pageSize为0则查询全部结果

#actuator,spring监控服务
management:
  endpoint:
    health:
      show-details: always   #显示健康具体信息  默认不会显示详细信息
  endpoints:
    web:
      base-path: /actuator   #修改访问路径
      exposure:
        include: "*"           #开放所有页面节点  默认只开启了health、info两个节点
    enabled-by-default: false
